export default {
    GAME_OVER_DELAY: 1500,
    KEYBOARD_BIN_VELOCITY: 600,
    KEYBOARD_BIN_VELOCITY_CHANGE: 150,
    COUNTER_MULTIPLIER_EFFECT: 1,
    INITIAL_ITEM_SPAWN_INTERVAL: 1200, // ms
    ITEM_SPAWN_INTERVAL_DECREASE: 25, //ms
    INITIAL_ITEM_FALL_VELOCITY: 10,
    ITEM_FALL_VELOCITY_INCREASE: 0.5
}